### ISSUE TITLE
"Runner.exe exited with non-zero status" with certain yaml files

### ISSUE THREAD

**Issue by ArendPeter** [JujuAdams/SNAP#35]
Hello,

I'm loading a yaml file at the start of my game using ``SnapFromYAML``, and then after a few minutes of playing the game I get the following error

```
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.4.0.113/windows/x64/Runner.exe exited with non-zero status (-1073741819)
```

At first I didn't think this was related to the yaml files but then I read [here](https://forum.gamemaker.io/index.php?threads/solved-need-help-runner-exe-exited-with-non-zero-status-1073741819-crash-when-reading-a-large-string-from-a-file.81141/) that the error is usually IO related and that the yaml library was the only IO in my game at the moment.

I found that a small tweak to my yaml made the error stop happening. Here's the 2 yaml varations

Version that caused the error

```
burn:
- {}
- duration_seconds: 2
  max_stack: 1
  dps: 1
-
  - max_stack+1
-
  - dps+1

freeze:
- {}
- duration_seconds: 2
  max_stack: 1
  slow_rate: .02
-
  - max_stack+1
-
  - slow_rate*1.5
```

Version that doesn't cause the error

```
burn:
- {}
- duration_seconds: 2
  max_stack: 1
  dps: 1
-
  - max_stack+1
-
  - dps+1



freeze:
- {}
- duration_seconds: 2
  max_stack: 1
  slow_rate: .02
-
  - max_stack+1
-
  - slow_rate*1.5
```

I made a git commit with this single change, then I went back and forth. The first variation consistently creates the error after a few minutes of gameplay, and the second one never creates this error

I used [this tool](https://onlineyamltools.com/convert-yaml-to-json) to verify that both yaml structures are identical, and I also verified that SNAP compiles the YAML correctly in both cases

My current theory theory is that SNAP doesn't clean up the resources properly after compiling the yaml in some cases, and this can cause errors down the line

I'm sorry I don't have more specific reproduction steps. I might try reproducing the error in a smaller project later this week, but for now I figured I'd report it anyway in case you had any ideas
